spring:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  # schema ? data DML DDL ?? ? ??

  datasource:
    #    url: jdbc:mysql://localhost:3306/chalkak?serverTimezone=UTC&charsetEncoding=UTF-8
    url: jdbc:h2:mem:petnuri;DB_CLOSE_DELAY=-1
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    #    username: root
    #    password: 1234
    username: sa
    password: