spring:
  config:
    import: env.yml

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${client-id}
            redirect-uri: http://localhost:8080/auth/kakao/login
            client-authentication-method: POST
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  redis:
    host: ${redis.ec2.host}
    port: 6379
    password: ${redis.ec2.password}